backend:
  name: git-gateway
  branch: main
  site_url: https://khet.text2.click

media_folder: "media"
public_folder: "/media"

collections:
  - name: "post"
    label: "Bài viết"
    folder: "post"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tiêu đề", name: "title", widget: "string" }
      - { label: "Mô tả", name: "description", widget: "text" }
      - { label: "Ảnh đại diện", name: "image", widget: "image" }
      - { label: "Nội dung", name: "body", widget: "markdown" }

  - name: "site-info"
    label: "Thông tin trang"
    files:
      - label: "Giới thiệu"
        name: "about"
        file: "site-info.md"
        fields:
          - { label: "Tiêu đề", name: "title", widget: "string" }
          - { label: "Mô tả", name: "description", widget: "text" }
